import { createClient } from "@/lib/supabase/server";
import { deviceForToken, parseBearerToken } from "@/lib/device-auth";
import { getDeviceConfig } from "@/lib/device-config-store";

// node:crypto hashes the token, so this cannot run on the Edge runtime.
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// Every answer, whatever its status: a cached config (or a cached 204) at the
// Vercel edge would hand one device's answer to the next poll.
const NO_STORE = { "Cache-Control": "no-store" } as const;

function empty(status: number, headers: Record<string, string> = {}): Response {
  return new Response(null, { status, headers: { ...NO_STORE, ...headers } });
}

/**
 * GET /api/config — called by the device, never by the dashboard.
 *
 * The request has no body: the device is identified by its per-device Bearer
 * token, which this application learns from the reports it POSTs to
 * /api/payloads (token hash -> device UID, see lib/device-auth).
 *
 * - 200: the device has a saved config. The body is the exact v0 file — ASCII,
 *   LF line endings, no BOM, no JSON wrapper — as `text/plain; charset=us-ascii`.
 * - 204: the token is known but no config is saved; the device keeps its own.
 * - 401: no Authorization header, or a token no report has been seen with.
 * - 500: anything else.
 *
 * Never redirects (the firmware does not follow redirects) and never logs the
 * Authorization header.
 */
export async function GET(request: Request) {
  const token = parseBearerToken(request.headers.get("authorization"));
  if (!token) return empty(401, { "WWW-Authenticate": "Bearer" });

  try {
    const supabase = await createClient();
    const deviceUid = await deviceForToken(supabase, token);
    if (!deviceUid) return empty(401, { "WWW-Authenticate": "Bearer" });

    const saved = await getDeviceConfig(supabase, deviceUid);
    if (!saved) return empty(204);

    // The file is generated by lib/remote-config and is pure ASCII; encode it
    // byte for byte rather than as UTF-8 so nothing can ever be re-encoded.
    const body = Buffer.from(saved.file, "latin1");
    return new Response(body, {
      status: 200,
      headers: {
        ...NO_STORE,
        "Content-Type": "text/plain; charset=us-ascii",
        "Content-Length": String(body.length),
      },
    });
  } catch (error) {
    console.error(
      "GET /api/config failed:",
      error instanceof Error ? error.message : "Unknown error",
    );
    return empty(500);
  }
}
